name: SSH Pull and Docker Compose

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.CLOUD_HOST_NAME }}
          username: ${{ secrets.CLOUD_USERNAME }}
          password: ${{ secrets.CLOUD_PASSWORD }}
          port: ${{ secrets.CLOUD_PORT }}
          script: mkdir test1 && mkdir test2

