name: SSH Pull and Docker Compose

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build and deploy app
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.CLOUD_HOST_NAME }}
          username: ${{ secrets.CLOUD_USERNAME }}
          password: ${{ secrets.CLOUD_PASSWORD }}
          port: ${{ secrets.CLOUD_PORT }}
          script: |
            mkdir repos
            cd repos
            git clone git@github.com:JoseSzycho/testCloudServer.git
            cd testCloudServer 
            git pull origin main
            docker compose down
            docker rmi testcloudserver-app
            docker compose up -d -e DATABASE_URL=$${{ secrets.DATABASE_URL }} -e NODE_ENV=${{ NODE_ENV }}


